version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: inflearn-clone-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - inflearn_clone_db:/var/lib/postgresql/data

volumes:
  inflearn_clone_db:
